# Change these first
owner: fwten # Your GitHub organization or username, where this repository lives
repo: hxgl-upptime # The name of this repository

sites:
  - name: HX GitLab
    url: https://healthx-gitlab.bihealth.org/
  - name: de.NBI LLM
    url: https://$DENBI_LLM_API/
  - name: de.NBI LLM API
    url: https://$DENBI_LLM_API/v1/
# disabled feb 2026
  - name: NFS Tar
    url: https://$HX_STATUS_PAGE/test/1/
    __dangerous__body_down: "false"
  - name: NFS Disk
    url: https://$HX_STATUS_PAGE/test/4/
    __dangerous__body_down: "false"
  - name: Local Disk
    url: https://$HX_STATUS_PAGE/test/5/
    __dangerous__body_down: "false"
# disabled years ago
  #- name: Aspera Conf
  #  url: https://$HX_STATUS_PAGE/test/2/
  #  __dangerous__body_down: "false"
  #- name: Aspera Tar
  #  url: https://$HX_STATUS_PAGE/test/3/
  #  __dangerous__body_down: "false"
  #- name: Aspera Log Tar
  #  url: https://$HX_STATUS_PAGE/test/6/
  #  __dangerous__body_down: "false"
  #- name: Aspera Log Conf
  #  url: https://$HX_STATUS_PAGE/test/7/
  #  __dangerous__body_down: "false"
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /hxgl-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
